### ISSUE TITLE
Improve configuration file structure and documentation

### ISSUE THREAD

**Issue by sebaslogen** [sebaslogen/corecito#26]
The configuration file is growing really fast and it's becoming complex to understand what each section of the config does.

The proposed goals:

1. Make it easy to understand
2. Make it scalable to add more variables
3. Support updating variables in runtime. Required for new features such as #11

Does anyone have comments about the goals? Something to change, add or remove?

As for possible solutions for each point here are some initial ideas:
1. Make it easy to understand:
 -- Add more documentation to variables: maybe to each variable with examples and sane default values
 -- Separate configuration variables in sections (possibly different files). FYI YAML supports sections and categories https://en.wikipedia.org/wiki/YAML#Syntax
2. Make it scalable to add more variables
 -- Similar to last point: separate configuration variables in sections (possibly different files). FYI YAML supports sections and categories https://en.wikipedia.org/wiki/YAML#Syntax - Here separation into files would make it even more scalable
3. Support updating variables in runtime
 -- Is YAML the correct data format to read/write? Will be ever have concurrent read/writes to it

**Comment by Leunam** [comment]
I have found this:
https://yaml.readthedocs.io/en/latest/overview.html
I'm gonna have a look right now and try some tests

**Comment by Leunam** [comment]
> 1. Make it easy to understand:
>    -- Add more documentation to variables: maybe to each variable with examples and sane default values
>    -- Separate configuration variables in sections (possibly different files). FYI YAML supports sections and categories https://en.wikipedia.org/wiki/YAML#Syntax

I agree

> 2. Make it scalable to add more variables
>    -- Similar to last point: separate configuration variables in sections (possibly different files). FYI YAML supports sections and categories https://en.wikipedia.org/wiki/YAML#Syntax - Here separation into files would make it even more scalable

```
---  # default config

api_key:
      public: <your Exchange API public key here>
      secret: <your Exchange API secret key here>

# EXCHANGE (Select which exchange you want to run Corecito on. Possible values -> 'crypto.com' or 'binance')
exchanges:
    - name: crypto.com
      trading_pair: ETH_BTC     # This must be one of the pairs listed in https://github.com/goincrypto/cryptocom-exchange/blob/master/src/cryptocom/exchange/pairs.py
      core_number_currency: ETH # this must be one of the currencies listed in https://github.com/goincrypto/cryptocom-exchange/blob/master/src/cryptocom/exchange/coins.py
      base_currency: BTC        # this must be one of the currencies listed in https://github.com/goincrypto/cryptocom-exchange/blob/master/src/cryptocom/exchange/coins.py
      max_decimals_buy: 6       # This is the limit Crypto.com has on ETH_BTC pair https://crypto.com/exchange/trade/spot/ETH_BTC
      max_decimals_sell: 3

    - name: binance
      trading_pair: ETHBTC      # This must be one of the pairs listed in Binance
      core_number_currency: ETH # This must be one of the coins listed in Binance
      base_currency: BTC        # This must be one of the coins listed in Binance
      max_decimals_buy: 6
      max_decimals_sell: 6

# CORE NUMBER SETTINGS
core_number:
    ammount: 2      # 1000 EUR, 1.123 ETH, etc...
    is_fiat: yes    # Yes  => If a trading pair involving Fiat or Stable Coin is used.  i.e. BTC/EUR, ETH/USDT, etc...
                    # No   => If a trading pair involving two cryptocurrencies is used. i.e. BTC/ETH, ADA/ETH, etc...
    min_increase_percentage: 3
    max_increase_percentage: 10
    min_decrease_percentage: 3
    max_decrease_percentage: 10

# These min and max price_stops are useful to stop corecito from selling or buying all your assets after many small deviations. Un/comment to enable/disable them.
# min_price_stop: 0.01 # Minimum price at which it stops making transactions.
# max_price_stop: 0.05 # Maximum price at which it stops making transactions.

# Core Number Wallet limits
core_number_wallet_limits:
      limit_core_number_wallet: yes
      max_core_number_wallet: 1000
      min_core_number_wallet: 500

# CORECITO MODES
running_mode:
    safe: yes # yes => no real trades will be made; no => real trades will be made
    test: yes # yes => Corecito will run just once; no => Corecito will run forever until stopped

# LOOP SETTINGS
seconds_between_iterations: 5

# TELEGRAM CONFIGURATION
telegram:
    send_notifications: yes # must be Yes or No
    send_errors: yes        # must be Yes or No
    bot_token: <bot token>
    user_id: <your user id> # In telegram app, search for '@userinfobot' and tap 'Start', it will reply with your user_id
```

What about something like this? It will require to adapt the code to the new structure. But it looks like this is the way.

> 3. Support updating variables in runtime
>    -- Is YAML the correct data format to read/write? Will be ever have concurrent read/writes to it

I got this one working, using [ruamel.yaml](https://yaml.readthedocs.io/en/latest/overview.html). Config file variables get updated without losing any comments.
I think that .yaml is a good format, way easier to read and understand than XML or JSON.
